// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: PowerMonitor

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void scroll_Animation(lv_obj_t * TargetObject, int delay);
void loading_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_header;
lv_obj_t * ui_headerico;
lv_obj_t * ui_Image4;
lv_obj_t * ui_vol;
lv_obj_t * ui_Image6;
lv_obj_t * ui_amp;
lv_obj_t * ui_aly;
lv_obj_t * ui_Image9;
lv_obj_t * ui_Image10;
lv_obj_t * ui_normalvol;
lv_obj_t * ui_overvoltage;
lv_obj_t * ui_clock;
lv_obj_t * ui_calendar;
lv_obj_t * ui_Image16;
lv_obj_t * ui_humi;
lv_obj_t * ui_temp;
lv_obj_t * ui_fanon;
lv_obj_t * ui_wifiok;
lv_obj_t * ui_wifierr;
lv_obj_t * ui_voltage;
lv_obj_t * ui_ampe;
lv_obj_t * ui_power;
lv_obj_t * ui_thongke;
lv_obj_t * ui_date;
lv_obj_t * ui_time;
lv_obj_t * ui_temp1;
lv_obj_t * ui_humi1;
lv_obj_t * ui_Sineico;
lv_obj_t * ui_sine;
lv_obj_t * ui_ipaddress;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Image11;
lv_obj_t * ui_Image8;
lv_obj_t * ui_ipIcon;
lv_obj_t * ui_energyRST;


// SCREEN: ui_startScr
void ui_startScr_screen_init(void);
void ui_event_startScr(lv_event_t * e);
lv_obj_t * ui_startScr;
lv_obj_t * ui_Image7;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_ampe_[1] = {&ui_img_ampe_1_png};
const lv_img_dsc_t * ui_imgset_calendar_[1] = {&ui_img_calendar_1_png};
const lv_img_dsc_t * ui_imgset_clockpng_[1] = {&ui_img_clockpng_1_png};
const lv_img_dsc_t * ui_imgset_coolingfan_[1] = {&ui_img_coolingfan_1_png};
const lv_img_dsc_t * ui_imgset_graphico_[1] = {&ui_img_graphico_1_png};
const lv_img_dsc_t * ui_imgset_humidity_[1] = {&ui_img_humidity_1_png};
const lv_img_dsc_t * ui_imgset_line_[4] = {&ui_img_line_2_png, &ui_img_line_4_png, &ui_img_line_5_png, &ui_img_line_6_png};
//const lv_img_dsc_t * ui_imgset_line_[1] = {&ui_img_line1_1_png};
const lv_img_dsc_t * ui_imgset_line_2[1] = {&ui_img_line1_2_png};
const lv_img_dsc_t * ui_imgset_overvoltage_[1] = {&ui_img_overvoltage_1_png};
const lv_img_dsc_t * ui_imgset_powermeter_[1] = {&ui_img_powermeter_1_png};
const lv_img_dsc_t * ui_imgset_pw_[1] = {&ui_img_pw_1_png};
const lv_img_dsc_t * ui_imgset_scr[1] = {&ui_img_scr1_png};
const lv_img_dsc_t * ui_imgset_temperature_[1] = {&ui_img_temperature_1_png};
const lv_img_dsc_t * ui_imgset_vol_[1] = {&ui_img_vol_1_png};
const lv_img_dsc_t * ui_imgset_voltnone_[1] = {&ui_img_voltnone_1_png};
const lv_img_dsc_t * ui_imgset_wifierr_[1] = {&ui_img_wifierr_1_png};
const lv_img_dsc_t * ui_imgset_wifiok_[1] = {&ui_img_wifiok_2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void scroll_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 2000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_width);
    lv_anim_set_values(&PropertyAnimation_0, 0, 80);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 10);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 1100);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 50);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 50);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_width);
    lv_anim_start(&PropertyAnimation_0);

}
void loading_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 255, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 1500);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_startScr(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 2000, &ui_Screen1_screen_init);
        loading_Animation(ui_Image7, 500);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_startScr_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
