// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: PowerMonitor

#ifndef _POWERMONITOR_UI_H
#define _POWERMONITOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void scroll_Animation(lv_obj_t * TargetObject, int delay);
void loading_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_header;
extern lv_obj_t * ui_headerico;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_vol;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_amp;
extern lv_obj_t * ui_aly;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_normalvol;
extern lv_obj_t * ui_overvoltage;
extern lv_obj_t * ui_clock;
extern lv_obj_t * ui_calendar;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_humi;
extern lv_obj_t * ui_temp;
extern lv_obj_t * ui_fanon;
extern lv_obj_t * ui_wifiok;
extern lv_obj_t * ui_wifierr;
extern lv_obj_t * ui_voltage;
extern lv_obj_t * ui_ampe;
extern lv_obj_t * ui_power;
extern lv_obj_t * ui_thongke;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_temp1;
extern lv_obj_t * ui_humi1;
extern lv_obj_t * ui_Sineico;
extern lv_obj_t * ui_sine;
extern lv_obj_t * ui_ipaddress;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_ipIcon;
extern lv_obj_t * ui_energyRST;
// SCREEN: ui_startScr
void ui_startScr_screen_init(void);
void ui_event_startScr(lv_event_t * e);
extern lv_obj_t * ui_startScr;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_contodien_png);    // assets/contodien.png
LV_IMG_DECLARE(ui_img_powermeter_1_png);    // assets/Powermeter 1.png
LV_IMG_DECLARE(ui_img_line_4_png);    // assets/Line 4.png
LV_IMG_DECLARE(ui_img_vol_1_png);    // assets/vol 1.png
LV_IMG_DECLARE(ui_img_pw_1_png);    // assets/pw 1.png
LV_IMG_DECLARE(ui_img_ampe_1_png);    // assets/ampe 1.png
LV_IMG_DECLARE(ui_img_graphico_1_png);    // assets/graphico 1.png
LV_IMG_DECLARE(ui_img_line_5_png);    // assets/Line 5.png
LV_IMG_DECLARE(ui_img_line_6_png);    // assets/Line 6.png
LV_IMG_DECLARE(ui_img_voltnone_1_png);    // assets/voltnone 1.png
LV_IMG_DECLARE(ui_img_overvoltage_1_png);    // assets/overvoltage 1.png
LV_IMG_DECLARE(ui_img_clockpng_1_png);    // assets/clockpng 1.png
LV_IMG_DECLARE(ui_img_calendar_1_png);    // assets/calendar 1.png
LV_IMG_DECLARE(ui_img_line_2_png);    // assets/Line 2.png
LV_IMG_DECLARE(ui_img_humidity_1_png);    // assets/humidity 1.png
LV_IMG_DECLARE(ui_img_temperature_1_png);    // assets/temperature 1.png
LV_IMG_DECLARE(ui_img_coolingfan_1_png);    // assets/coolingfan 1.png
LV_IMG_DECLARE(ui_img_wifiok_2_png);    // assets/wifiok 2.png
LV_IMG_DECLARE(ui_img_wifierr_1_png);    // assets/wifierr 1.png
LV_IMG_DECLARE(ui_img_sine_png);    // assets/sine.png
LV_IMG_DECLARE(ui_img_line1_1_png);    // assets/line1.1.png
LV_IMG_DECLARE(ui_img_line1_2_png);    // assets/Line1.2.png
LV_IMG_DECLARE(ui_img_ipaddress_png);    // assets/ipaddress.png
LV_IMG_DECLARE(ui_img_fame_png);    // assets/fame.png
LV_IMG_DECLARE(ui_img_scr1_png);    // assets/scr1.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
