// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: PowerMonitor

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_header, &ui_img_contodien_png);
    lv_obj_set_width(ui_header, LV_SIZE_CONTENT);   /// 166
    lv_obj_set_height(ui_header, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_header, -20);
    lv_obj_set_y(ui_header, -75);
    lv_obj_set_align(ui_header, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_header, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_header, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_headerico = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_headerico, &ui_img_powermeter_1_png);
    lv_obj_set_width(ui_headerico, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_headerico, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_headerico, 87);
    lv_obj_set_y(ui_headerico, -74);
    lv_obj_set_align(ui_headerico, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_headerico, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_headerico, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image4, &ui_img_line_4_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 220
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_x(ui_Image4, -1);
    lv_obj_set_y(ui_Image4, -56);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_vol = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_vol, &ui_img_vol_1_png);
    lv_obj_set_width(ui_vol, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_vol, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_vol, -94);
    lv_obj_set_y(ui_vol, -39);
    lv_obj_set_align(ui_vol, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_vol, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_vol, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image6, &ui_img_pw_1_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_Image6, -98);
    lv_obj_set_y(ui_Image6, -9);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_amp = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_amp, &ui_img_ampe_1_png);
    lv_obj_set_width(ui_amp, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_amp, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_amp, -3);
    lv_obj_set_y(ui_amp, -40);
    lv_obj_set_align(ui_amp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_amp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_amp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aly = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_aly, &ui_img_graphico_1_png);
    lv_obj_set_width(ui_aly, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_aly, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_aly, 10);
    lv_obj_set_y(ui_aly, 10);
    lv_obj_set_align(ui_aly, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aly, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aly, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image9, &ui_img_line_5_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_x(ui_Image9, 67);
    lv_obj_set_y(ui_Image9, -32);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image10, &ui_img_line_6_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 44
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_x(ui_Image10, 88);
    lv_obj_set_y(ui_Image10, -10);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_normalvol = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_normalvol, &ui_img_voltnone_1_png);
    lv_obj_set_width(ui_normalvol, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_normalvol, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_normalvol, 90);
    lv_obj_set_y(ui_normalvol, -34);
    lv_obj_set_align(ui_normalvol, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_normalvol, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_normalvol, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_overvoltage = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_overvoltage, &ui_img_overvoltage_1_png);
    lv_obj_set_width(ui_overvoltage, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_overvoltage, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_overvoltage, 90);
    lv_obj_set_y(ui_overvoltage, -34);
    lv_obj_set_align(ui_overvoltage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_overvoltage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_overvoltage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clock = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_clock, &ui_img_clockpng_1_png);
    lv_obj_set_width(ui_clock, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_clock, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_clock, -96);
    lv_obj_set_y(ui_clock, 49);
    lv_obj_set_align(ui_clock, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clock, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_clock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_calendar = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_calendar, &ui_img_calendar_1_png);
    lv_obj_set_width(ui_calendar, LV_SIZE_CONTENT);   /// 19
    lv_obj_set_height(ui_calendar, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_x(ui_calendar, -97);
    lv_obj_set_y(ui_calendar, 74);
    lv_obj_set_align(ui_calendar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_calendar, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_calendar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image16 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image16, &ui_img_line_2_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 67
    lv_obj_set_x(ui_Image16, 1);
    lv_obj_set_y(ui_Image16, 56);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_humi = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_humi, &ui_img_humidity_1_png);
    lv_obj_set_width(ui_humi, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_humi, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_humi, 13);
    lv_obj_set_y(ui_humi, 68);
    lv_obj_set_align(ui_humi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_humi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_humi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temp = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_temp, &ui_img_temperature_1_png);
    lv_obj_set_width(ui_temp, LV_SIZE_CONTENT);   /// 19
    lv_obj_set_height(ui_temp, LV_SIZE_CONTENT);    /// 19
    lv_obj_set_x(ui_temp, 13);
    lv_obj_set_y(ui_temp, 39);
    lv_obj_set_align(ui_temp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_temp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_temp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fanon = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_fanon, &ui_img_coolingfan_1_png);
    lv_obj_set_width(ui_fanon, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_fanon, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_fanon, 97);
    lv_obj_set_y(ui_fanon, 41);
    lv_obj_set_align(ui_fanon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fanon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fanon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiok = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_wifiok, &ui_img_wifiok_2_png);
    lv_obj_set_width(ui_wifiok, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_wifiok, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_wifiok, 98);
    lv_obj_set_y(ui_wifiok, 71);
    lv_obj_set_align(ui_wifiok, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiok, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifiok, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifierr = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_wifierr, &ui_img_wifierr_1_png);
    lv_obj_set_width(ui_wifierr, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_wifierr, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_wifierr, 98);
    lv_obj_set_y(ui_wifierr, 71);
    lv_obj_set_align(ui_wifierr, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifierr, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifierr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_voltage = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_voltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_voltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_voltage, -48);
    lv_obj_set_y(ui_voltage, -36);
    lv_obj_set_align(ui_voltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_voltage, "228.5V");
    lv_obj_set_style_text_color(ui_voltage, lv_color_hex(0xF43333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_voltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_voltage, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ampe = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ampe, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ampe, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ampe, 36);
    lv_obj_set_y(ui_ampe, -40);
    lv_obj_set_align(ui_ampe, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ampe, " 10.2A");
    lv_obj_set_style_text_color(ui_ampe, lv_color_hex(0xFFCF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ampe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ampe, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_power = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_power, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_power, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_power, -48);
    lv_obj_set_y(ui_power, -8);
    lv_obj_set_align(ui_power, LV_ALIGN_CENTER);
    lv_label_set_text(ui_power, "1000.4W");
    lv_obj_set_style_text_color(ui_power, lv_color_hex(0xFF12FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_power, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_thongke = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_thongke, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_thongke, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_thongke, 68);
    lv_obj_set_y(ui_thongke, 9);
    lv_obj_set_align(ui_thongke, LV_ALIGN_CENTER);
    lv_label_set_text(ui_thongke, "10000.5W");
    lv_obj_set_style_text_color(ui_thongke, lv_color_hex(0x00FF1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_thongke, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_thongke, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, -42);
    lv_obj_set_y(ui_date, 74);
    lv_obj_set_align(ui_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date, "12/12/2024");
    lv_obj_set_style_text_color(ui_date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, -46);
    lv_obj_set_y(ui_time, 50);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "24:00");
    lv_obj_set_style_text_color(ui_time, lv_color_hex(0x00FFE2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_temp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp1, 52);
    lv_obj_set_y(ui_temp1, 40);
    lv_obj_set_align(ui_temp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp1, "50*C");
    lv_obj_set_style_text_color(ui_temp1, lv_color_hex(0xF937D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temp1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humi1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_humi1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humi1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humi1, 49);
    lv_obj_set_y(ui_humi1, 68);
    lv_obj_set_align(ui_humi1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humi1, "65%");
    lv_obj_set_style_text_color(ui_humi1, lv_color_hex(0x0088FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humi1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humi1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sineico = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Sineico, &ui_img_sine_png);
    lv_obj_set_width(ui_Sineico, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Sineico, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Sineico, 3);
    lv_obj_set_y(ui_Sineico, -14);
    lv_obj_set_align(ui_Sineico, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Sineico, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Sineico, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Sineico, 240);

    ui_sine = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_sine, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sine, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sine, 39);
    lv_obj_set_y(ui_sine, -15);
    lv_obj_set_align(ui_sine, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sine, "60.5Hz");
    lv_obj_set_style_text_color(ui_sine, lv_color_hex(0x10FBF0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sine, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ipaddress = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ipaddress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ipaddress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ipaddress, -53);
    lv_obj_set_y(ui_ipaddress, 20);
    lv_obj_set_align(ui_ipaddress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ipaddress, "192.168.255.255");
    lv_obj_set_style_text_color(ui_ipaddress, lv_color_hex(0xFFB700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ipaddress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        // Tạo animation cho scroll
    lv_anim_t anim;
    lv_anim_init(&anim);
    lv_anim_set_var(&anim, ui_ipaddress);
    lv_anim_set_values(&anim, -50, -100);
    lv_anim_set_time(&anim, 2000);     // Thời gian animation là 2000ms
    lv_anim_set_exec_cb(&anim, (lv_anim_exec_xcb_t) lv_obj_set_x);
    lv_anim_set_path_cb(&anim, lv_anim_path_linear); // Đường đi linear
    lv_anim_set_repeat_count(&anim, LV_ANIM_REPEAT_INFINITE);
    lv_anim_start(&anim);

    ui_Image5 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image5, &ui_img_line1_1_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 116
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_x(ui_Image5, 58);
    lv_obj_set_y(ui_Image5, 22);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image11, &ui_img_line1_2_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 141
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_x(ui_Image11, -80);
    lv_obj_set_y(ui_Image11, 10);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image8, &ui_img_line1_2_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 141
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_x(ui_Image8, -71);
    lv_obj_set_y(ui_Image8, 32);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ipIcon = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ipIcon, &ui_img_ipaddress_png);
    lv_obj_set_width(ui_ipIcon, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_ipIcon, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_ipIcon, -10);
    lv_obj_set_y(ui_ipIcon, 18);
    lv_obj_set_align(ui_ipIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ipIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ipIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_energyRST = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_energyRST, &ui_img_fame_png);
    lv_obj_set_width(ui_energyRST, LV_SIZE_CONTENT);   /// 120
    lv_obj_set_height(ui_energyRST, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_energyRST, 3);
    lv_obj_set_y(ui_energyRST, -1);
    lv_obj_set_align(ui_energyRST, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_energyRST, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_energyRST, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
