// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: PowerMonitor

#include "ui.h"

void ui_startScr_screen_init(void)
{
    ui_startScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_startScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_startScr);
    lv_img_set_src(ui_Image7, &ui_img_scr1_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 220
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 176
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_startScr, ui_event_startScr, LV_EVENT_ALL, NULL);

}
